languageCode = "en"
languageName = "English"
weight = 1
title = "BinaryDigit"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "Jan 2 2006"
  logo = "img/michigan-flation.png"
  secondaryLogo = "img/statue-of-liberty-flaticon.png"
  description = "BinaryDigit's Digital Cafe"
  copyright = '<script src="https://status.lol/binarydigit.js?time&link&no-emoji"></script>'

 [author]
   name = "BinaryDigit"
   image = "img/AvatarByAndyCarolan3.png"
   headline = "A digital cafe of hobbies, projects and notes"
   bio = "B's digital cafe of hobbies, projects and notes"
   links = [
      { mug-hot = "https://blog.binarydigit.cafe" },
      { envelope = "mailto:hi[at]binarydigit.cafe" },
      { twitch = "https://www.twitch.tv/BinaryDigit/" },
      { youtube = "https://youtube.com/@BinaryDigit/" },
      { music = "https://hearthis.at/binarydigitdj/" },
      { peertube = "https://makertube.net/a/binarydigit/"},  
      { mastodon = "https://social.lol/@BinaryDigit/" },
      { image = "https://glass.photo/binarydigit" },
      { github = "https://github.com/BinaryPixels/" },  
      { prami = "https://links.binarydigit.cafe/" },
   ]
