languageCode = "en"
languageName = "English"
weight = 1
title = "The Cafe"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "Jan 2 2006"
logo = "img/michigan-flation.png"
secondaryLogo = "img/statue-of-liberty-flaticon.png"
description = "BinaryDigit's Digital Cafe"
copyright = '<script src="https://status.lol/binarydigit.js?time&link&no-emoji"></script>'

[author]
name = "BinaryDigit"
image = "img/AvatarByAndyCarolan1.png"
headline = "A digital cafe of hobbies, projects and notes"
bio = "A digital cafe of hobbies, projects and notes"
links = [
    { microdotblog = "https://blog.binarydigit.cafe" },
    { twitch = "https://www.twitch.tv/BinaryDigit/" },
    { mastodon = "https://social.lol/@BinaryDigit/" },
    { youtube = "https://youtube.com/@BinaryDigit/" },
    { music = "https://hearthis.at/binarydigitdj/" },
    { peertube = "https://makertube.net/a/binarydigit/" },
    { image = "https://glass.photo/binarydigit" },
    { prami = "https://links.binarydigit.cafe/" },
    { envelope = "/about" },
    { ko-fi = "https://ko-fi.com/binarydigit/" },
]
