languageCode = "en"
languageName = "English"
weight = 1
title = "BinaryDigit"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "Jan 2 2006"
  logo = "img/CoffeeCroissantByFreepik.png"
  secondaryLogo = "img/CoffeeCroissantByFreepik.png"
  description = "BinaryDigit's Digital Cafe"
  copyright = 'Current Status: <script src="https://status.lol/binarydigit.js?time&link&no-emoji"></script>'

 [author]
   name = "BinaryDigit"
   image = "img/AvatarByAndyCarolan2.png"
   headline = "A digital cafe of hobbies, projects and notes"
   bio = "B's digital cafe of hobbies, projects and notes"
   links = [
      { envelope = "mailto:hi[at]binarydigit.cafe" },
      { mastodon = "https://social.lol/@BinaryDigit/" },
      { image = "https://glass.photo/binarydigit" },
      { github = "https://github.com/BinaryPixels/" },  
      { twitch = "https://www.twitch.tv/BinaryDigit/" },
      { youtube = "https://youtube.com/@BinaryDigit/" },
      { peertube = "https://makertube.net/a/binarydigit/"},  
      { prami = "https://links.binarydigit.cafe/" },     
      { ko-fi = "https://ko-fi.com/binarydigit/" },
   ]
