# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Notes"
  pre = "pencil"
  pageRef = "/notes"
  weight = 10

[[main]]
  name = "Twitch"
  pre = "twitch"
  pageRef = "/twitch"
  weight = 50

[[main]]
  name = "Music"
  pre = "music"
  pageRef = "/music"
  weight = 60

[[main]]
  name = "Projects"
  pre = "lightbulb"
  pageRef = "/projects"
  weight = 70

[[main]]
  name = "About"
  pre = "circle-info"
  pageRef = "/about"
  weight = 80

[[main]]
 name = ""
 pre = "rss"
url = "https://binarydigit.cafe/index.xml"
 weight = 90

[[subnavigation]]
 name = "Categories"
 pre = "bars"
 pageRef = "categories"
 weight = 10

 [[subnavigation]]
 name = "Tags"
 pre = "tag"
 pageRef = "tags"
 weight = 20

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 10

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 20
