[[redirects]]
  from = "/.well-known/host-meta*"
  to = "https://fed.brid.gy/.well-known/host-meta:splat"
  status = 302
[[redirects]]
  from = "/.well-known/webfinger*"
  to = "https://fed.brid.gy/.well-known/webfinger"
  status = 302
[[redirects]]
  from = "/now"
  to = "https://links.binarydigit.cafe/now"
  status = 301
[[redirects]]
  from = "/discord"
  to = "https://discord.gg/KjVdUgz4wb"
  status = 301
[[redirects]]
  from = "/rewrite/*"
  to = "https://:splat"
  status = 200
